---
calibre:
  add: 
    automerge:
    duplicates: true
    empty:  #false
  add_from_folders:
    add:
    ignore:
    one_book_per_directory:  #false
    recurse: # false
  add_format: 
    dont_replace: true
  embed_metadata: 
    only_formats:
  export: 
    dont_asciiize:  #false
    dont_save_cover:  #false
    dont_update_metadata:  #false
    dont_write_opf: true
    formats:
    replace_whitespace: true
    single_dir:  #false
    timefmt:
    to_dir:
    to_lowercase:  #false
    template:
  list: 
    ascending:  #false
    fields: ["author_sort", "authors", "comments", "cover", "formats", "identifiers", "isbn", "languages", "last_modified", "pubdate", "publisher", "rating", "series", "series_index", "size", "tags", "timestamp", "title", "uuid", "all"]
    for_machine: true
    search:
    sort_by:
  remove: 
    permanent:  #false
  remove_custom_column: 
    force:  #false
