// Code generated by github.com/switchupcb/copygen
// DO NOT EDIT.

package cdb

type SavedSearchesAdd struct {
	*Command
}

type EmbedMetadata struct {
	*Command
}

func (c *EmbedMetadata) OnlyFormats() *EmbedMetadata {
	c.SetFlags("--only_formats")
	return c
}

type Remove struct {
	*Command
}

func (c *Remove) Permanent() *Remove {
	c.SetFlags("--permanent")
	return c
}

type RemoveFormat struct {
	*Command
}

type SetMetadata struct {
	*Command
}

func (c *SetMetadata) Field(v string) *SetMetadata {
	c.SetFlags("--field", v)
	return c
}

func (c *SetMetadata) ListFields() *SetMetadata {
	c.SetFlags("--list_fields")
	return c
}

type ShowMetadata struct {
	*Command
}

func (c *ShowMetadata) AsOpf() *ShowMetadata {
	c.SetFlags("--as_opf")
	return c
}

type SavedSearchesList struct {
	*Command
}

type SavedSearchesRemove struct {
	*Command
}

type Add struct {
	*Command
}

func (c *Add) Add(v string) *Add {
	c.SetFlags("--add", v)
	return c
}

func (c *Add) Automerge() *Add {
	c.SetFlags("--automerge")
	return c
}

func (c *Add) Duplicates() *Add {
	c.SetFlags("--duplicates")
	return c
}

func (c *Add) Empty() *Add {
	c.SetFlags("--empty")
	return c
}

func (c *Add) Ignore(v string) *Add {
	c.SetFlags("--ignore", v)
	return c
}

func (c *Add) OneBookPerDirectory() *Add {
	c.SetFlags("--one_book_per_directory")
	return c
}

func (c *Add) Recurse() *Add {
	c.SetFlags("--recurse")
	return c
}

type AddFormat struct {
	*Command
}

func (c *AddFormat) DontReplace() *AddFormat {
	c.SetFlags("--dont_replace")
	return c
}

type Export struct {
	*Command
}

func (c *Export) DontAsciiize() *Export {
	c.SetFlags("--dont_asciiize")
	return c
}

func (c *Export) DontSaveCover() *Export {
	c.SetFlags("--dont_save_cover")
	return c
}

func (c *Export) DontUpdateMetadata() *Export {
	c.SetFlags("--dont_update_metadata")
	return c
}

func (c *Export) DontWriteOpf() *Export {
	c.SetFlags("--dont_write_opf")
	return c
}

func (c *Export) Formats(v string) *Export {
	c.SetFlags("--formats", v)
	return c
}

func (c *Export) ReplaceWhitespace() *Export {
	c.SetFlags("--replace_whitespace")
	return c
}

func (c *Export) SingleDir() *Export {
	c.SetFlags("--single_dir")
	return c
}

func (c *Export) Template(v string) *Export {
	c.SetFlags("--template", v)
	return c
}

func (c *Export) Timefmt(v string) *Export {
	c.SetFlags("--timefmt", v)
	return c
}

func (c *Export) ToDir(v string) *Export {
	c.SetFlags("--to_dir", v)
	return c
}

func (c *Export) ToLowercase() *Export {
	c.SetFlags("--to_lowercase")
	return c
}	
	